name: Main

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag'     
        required: true
        default: 'warning'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          cp scripts/command.sh asd.sh
          cp scripts/install.sh install.sh
      - name: Test
        run: ls
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tagname: github.event.inputs.tags
          generate_release_notes: true
          draft: true
          files: |
            asd.sh
            install.sh
